# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouTubeSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTubeSample

  target 'YouTubeSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouTubeSampleUITests' do
    # Pods for testing
  end

pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON'
pod 'youtube-ios-player-helper', '~> 1.0.2'
pod 'SDWebImage', '~> 5.0'
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'

end
