# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OriginalApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OriginalApp

  pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git', :branch => 'develop'
  pod 'NYXImagesKit'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'EMTNeumorphicView'
  pod 'RAMAnimatedTabBarController'
  
  


end
